# Generated by Django 4.2.7 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
        ),
    ]
