# Generated by Django 4.2.7 on 2023-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bmi_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
