# Generated by Django 4.2.7 on 2023-12-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0, verbose_name='weight'),
        ),
    ]
