# Generated by Django 4.2.7 on 2023-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bmi_user_bmi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
