# Generated by Django 4.2.7 on 2023-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bmi_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi_comparison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
