# Generated by Django 4.2.7 on 2023-12-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bmi_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bmi_comparison',
        ),
        migrations.AddField(
            model_name='user',
            name='bmi_trend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
