# Generated by Django 4.2.7 on 2023-11-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_choice_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesAllergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Allergy',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AddField(
            model_name='choicesallergies',
            name='allergies_choices',
            field=models.ManyToManyField(to='home.allergy'),
        ),
    ]
