# Generated by Django 4.2.7 on 2023-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity_input',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
