# Generated by Django 4.2.7 on 2023-11-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_choicesallergies_rename_choice_allergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesallergies',
            name='allergies_choices',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='ChoicesAllergies',
        ),
    ]
