# Generated by Django 4.2.7 on 2023-12-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_basket_quantity_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='quantity_input',
        ),
    ]
